config/routes.rb
Rails.application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users
  resources :sessions

  resources :categories
  resources :sub_categories
  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
  CATEGORY_TYPES = ["a", "b"]
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :sub_category
  PRODUCT_TYPES = ["a", "b"]
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  has_many :products, dependent: :destroy
  belongs_to :category
  SUBCATEGORY_TYPES = ["a", "b"]
end

app/models/user.rb
class User < ActiveRecord::Base
 #attr_accessible :email, :password, :password_confirmation 
  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new 
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category  = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id]) 
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :cat_type,:image,:remote_image_url)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new 
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
    @product  = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def show
    @product = Product.find(params[:id]) 
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name,:brand,:prod_type,:price,:discount,:description,:ratings,:emi,:delivery_type,:offers,:cash_on_delivery,:guarantee,:specs,:review,:instock,:out_of_stock,:category_id,:sub_category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.authenticate(params[:email],params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def index
    @subcategories = SubCategory.all
  end

  def new
    @subcategory = SubCategory.new 
  end

  def create
    @subcategory = SubCategory.new(sub_category_params)
    if @subcategory.save
      redirect_to @subcategory
    else
      render 'new'
    end
  end

  def edit
    @subcategory  = SubCategory.find(params[:id])
  end

  def update
    @subcategory = SubCategory.find(params[:id])

    if @subcategory.update(sub_category_params)
      redirect_to @subcategory
    else
      render 'edit'
    end
  end

  def show
    @subcategory = SubCategory.find(params[:id]) 
  end
  def destroy
    @subcategory = SubCategory.find(params[:id])
    @subcategory.destroy

    redirect_to sub_categories_path
  end

  private
  def sub_category_params
    params.require(:sub_category).permit(:name, :sub_cat_type,:category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.encrypt_password
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category,:html =>{:multipart => true} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cat_type %>
    <%= f.select(:cat_type, Category::CATEGORY_TYPES) %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image  %>
  </div>

  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing SubCategory</h1>
<table>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Category Type</th>
      <th>Category Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.cat_type %></td>
        <td><%= category.image_url %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Category_type:</strong>
  <%= @category.cat_type %>
</p>

<p>
  <strong>Category image:</strong>
  <%= image_tag @category.image_url if @category.image? %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminScratch</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash#{name}" %>
    <% end %>

    <div id="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>
        <%= link_to "Log out", log_out_path %>
      <% else %>
        <%= link_to "Sign up", sign_up_path %> or 
        <%= link_to "Log in", log_in_path %>
      <% end %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]} %>
  </div>
  <div class="field">
    <%= f.label :sub_category %><br>
    <%= f.select :sub_category_id, SubCategory.all.collect {|x| [x.name, x.id]} %>
  </div>

  <div class="field">
    <%= f.label :prod_type %>
    <%= f.select(:prod_type, Product::PRODUCT_TYPES) %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :ratings %><br>
    <%= f.text_field :ratings %>
  </div>
  <div class="field">
    <%= f.label :emi %><br>
    <%= f.text_field :emi %>
  </div>
  <div class="field">
    <%= f.label :delivery_type %><br>
    <%= f.text_field :delivery_type %>
  </div>
  <div class="field">
    <%= f.label :offers %><br>
    <%= f.text_field :offers %>
  </div>
  <div class="field">
    <%= f.label :cash_on_delivery %><br>
    <%= f.text_field :cash_on_delivery %>
  </div>
  <div class="field">
    <%= f.label :guarantee %><br>
    <%= f.text_field :guarantee %>
  </div>
  <div class="field">
    <%= f.label :specs %><br>
    <%= f.text_field :specs %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_field :review %>
  </div>
  <div class="field">
    <%= f.label :instock %><br>
    <%= f.text_field :instock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Product</h1>
<table>
  <thead>
    <tr>
      <th> Name</th>
      <th>Brand</th>
      <th>Type</th>
      <th>Price</th>
      <th>category</th>
      <th>sub category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.prod_type %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
        <td><%= product.sub_category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Sub Category:</strong>
  <%= @product.sub_category.name %>
</p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Brand</strong>
  <%= @product.brand %>
</p>
<p>
  <strong>Type:</strong>
  <%= @product.prod_type %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Discount:</strong>
  <%= @product.discount %>
</p>
<p>
  <strong>Description</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Ratings</strong>
  <%= @product.ratings %>
</p>
<p>
  <strong>Emi:</strong>
  <%= @product.emi %>
</p>
<p>
  <strong>Delivery Type</strong>
  <%= @product.delivery_type %>
</p>
<p>
  <strong>Offers</strong>
  <%= @product.offers %>
</p>
<p>
  <strong>Cash on Delivery:</strong>
  <%= @product.cash_on_delivery %>
</p>
<p>
  <strong>Guarantee</strong>
  <%= @product.guarantee %>
</p>
<p>
  <strong>Specs:</strong>
  <%= @product.specs %>
</p>
<p>
  <strong>Review:</strong>
  <%= @product.review %>
</p>
<p>
  <strong>Instock:</strong>
  <%= @product.instock %>
</p>

<p>
  <strong>Out Of Stock:</strong>
  <%= @product.out_of_stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sub_categories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
      <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]} %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sub_cat_type %>
    <%= f.select(:sub_cat_type, SubCategory::SUBCATEGORY_TYPES) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing SubCategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<h1>Listing SubCategory</h1>
<table>
  <thead>
    <tr>
      <th>SubCategory Name:</th>
      <th>SubCategory Type:</th>
      <th>Category Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.sub_cat_type %></td>
        <td><%= sub_category.category.name %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New SubCategory</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>SUb Category type:</strong>
  <%= @subcategory.sub_cat_type %>
</p>

<p>
  <strong>Category Name:</strong>
  <%= @subcategory.category.name %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@subcategory) %> |
<%= link_to 'Back', sub_categories_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>